[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/deoplete.nvim'
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]] repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'pangloss/vim-javascript'
[[plugins]]
repo = 'mxw/vim-jsx'
[[plugins]]
repo = 'posva/vim-vue'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf', 'terraform']
hook_source = '''
let g:terraform_fmt_on_save=1
'''
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'mattn/vim-lsp-settings'
[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'preservim/nerdtree'
[[plugins]]
repo = 'mattn/vim-goimports'
[[plugins]]
repo = 'ibhagwan/fzf-lua'
[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'
[[plugins]]
repo = 'rhysd/vim-go-impl'
[[plugins]]
repo = 'github/copilot.vim'
